import { useEffect, useState } from 'react';
import { invoke, listen } from './transport';
import type { ContextId } from './types';
interface Step { id: string; tool: string; args: Record<string, unknown>; depends_on?: string[]; }
interface Spec { name: string; kind: string; context_id: ContextId; description: string; completion_contract: string; tools: string[]; steps: Step[]; }
interface Receipt { run_id: string; mode: string; status: string; evidence_class?: string; error?: string; change_state?: string; outputs?: Record<string, unknown>; steps?: Array<{ id: string; tool: string; status: string; output: unknown }>; }
interface Capability { capability_id: string; name?: string; kind: string; status: string; spec: Spec; latest_run?: Receipt; }
interface Job { job_id: string; capability_id: string; spec: Spec; status: string; mode: string; timezone: string; next_run?: string; last_run?: string; last_status?: string; last_result?: Receipt; schedule: { kind: string; time?: string; weekday?: number }; }
const workspace = <T,>(operation: string, request: Record<string, unknown> = {}) => invoke<T>('workspace_operation', { operation, request });
export function makeWorkflow(name: string, description: string, context: ContextId, evidenceQuery: string, includeTasks: boolean): Spec {
  const steps: Step[] = [];
  if (includeTasks) steps.push({ id: 'tasks', tool: 'list_tasks', args: {} });
  if (evidenceQuery.trim()) steps.push({ id: 'evidence', tool: 'search_evidence', args: { query: evidenceQuery.trim(), limit: 50 } });
  if (!steps.length) throw new Error('Choose tasks or provide an evidence question.');
  steps.push({ id: 'report', tool: 'save_output', depends_on: steps.map(step => step.id), args: { title: name, content: { objective: description, ...Object.fromEntries(steps.map(step => [step.id, { from_step: step.id }])) } } });
  return { name, description, kind: 'workflow', context_id: context, completion_contract: 'Collect the selected scoped records and retain their source data in a local review output.', tools: [...new Set(steps.map(step => step.tool))], steps };
}
export function AutomationWorkspace({ context, view }: { context: ContextId; view: 'Teach Jarvis' | 'Missions' | 'Radars' }) {
  const [capabilities, setCapabilities] = useState<Capability[]>([]);
  const [jobs, setJobs] = useState<Job[]>([]);
  const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [selected, setSelected] = useState<Capability | null>(null);
  const [receipt, setReceipt] = useState<Receipt | null>(null);
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [query, setQuery] = useState('');
  const [tasks, setTasks] = useState(true);
  const [schedule, setSchedule] = useState('weekly');
  const [time, setTime] = useState('09:00');
  const [weekday, setWeekday] = useState('4');
  const [zone, setZone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC');
  const [mode, setMode] = useState('shadow');
  const [lifecycle, setLifecycle] = useState('off');
  async function refresh() {
    const [caps, ownedJobs] = await Promise.all([workspace<{ data: Capability[] }>('capabilities.list', { context }), workspace<{ data: Job[]; lifecycle?: string }>('jobs.list', { context })]);
    setCapabilities(caps.data ?? []); setJobs(ownedJobs.data ?? []); setLifecycle(ownedJobs.lifecycle ?? "off");
  }
  useEffect(() => { setSelected(null); setReceipt(null); void refresh().catch(error => setNotice(`Automation unavailable: ${String(error)}`)); }, [context]);
  useEffect(() => { const stop = listen('jarvis-workspace-updated', () => { void refresh().catch(() => undefined); }); return () => { void stop.then(fn => fn()); }; }, [context]);
  async function perform(work: () => Promise<void>) {
    if (busy) return; setBusy(true); setNotice('');
    try { await work(); } catch (error) { setNotice(String(error)); } finally { setBusy(false); }
  }
  async function execute(mode: 'dry' | 'shadow' | 'active') {
    if (!selected) return;
    await perform(async () => {
      // Synthetic inputs are explicit data, not a pretend successful provider query.
      const fixtures = Object.fromEntries((selected.spec.steps ?? []).filter(step => !['save_output', 'create_task'].includes(step.tool)).map(step => [step.id, [{ title: 'Synthetic review item', source: 'isolated UI fixture', status: 'open' }]]));
      const result = await workspace<Receipt>('capabilities.run', { capabilityId: selected.capability_id, mode, ...(mode === 'dry' ? { fixtures } : {}) });
      setReceipt(result); await refresh(); setNotice(result.status === 'completed' ? `${mode === 'dry' ? 'Fixture execution' : mode === 'shadow' ? 'Read-only shadow execution' : 'Local workflow execution'} completed. Review its actual steps below.` : `Execution ${result.status}: ${result.error ?? 'Check the result below.'}`);
    });
  }
  const selectedCurrent = capabilities.find(item => item.capability_id === selected?.capability_id) ?? selected;
  return <section className="automation-workspace"><div className="workspace-intro"><p className="eyebrow">{view}</p><h2>{view === 'Teach Jarvis' ? 'A procedure you can actually run' : view === 'Radars' ? 'Watch for meaningful changes' : 'Keep a job moving'}</h2><p>Build a local review from tasks and saved evidence, test it, then run or schedule its tested version. A failed check is never reported as no change.</p><button className="quiet" disabled={busy} onClick={() => void perform(refresh)}>Refresh executions</button></div>
    {notice && <p className="workspace-notice" role="status">{notice}</p>}
    <div className="management-columns"><section className="card surface"><h3>Your procedures</h3><div className="item-list">{capabilities.map(item => <article key={item.capability_id}><strong>{item.spec?.name ?? item.name ?? 'Unnamed procedure'}</strong><p>{item.status} · {item.spec?.steps?.length ?? 0} executable steps</p><button className="quiet" onClick={() => { setSelected(item); setReceipt(item.latest_run ?? null); }}>Open procedure</button></article>)}{!capabilities.length && <p>No procedure is available in this context. Define the records to gather below.</p>}</div>
      <details open={!capabilities.length || Boolean(editingId)}><summary>Create a review procedure</summary><form className="local-create" onSubmit={event => { event.preventDefault(); void perform(async () => { const spec = makeWorkflow(name, description, context, query, tasks); const result = await workspace<{ capability_id: string }>(editingId ? 'capabilities.revise' : 'capabilities.create', { spec, ...(editingId ? { capabilityId: editingId } : {}) }); await refresh(); setSelected({ capability_id: result.capability_id, kind: 'workflow', status: 'draft', spec }); setName(''); setDescription(''); setEditingId(null); setReceipt(null); setNotice('Executable procedure saved as a draft. Run fixtures and shadow before activation.'); }); }}><label>Name<input value={name} onChange={event => setName(event.target.value)} placeholder="Friday project review" required/></label><label>What should this help you decide?<textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="Check open work and identify records that need my review." required/></label><label className="checkbox-row"><input type="checkbox" checked={tasks} onChange={event => setTasks(event.target.checked)}/>Include current tasks</label><label>Evidence to find<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Optional: project planning decisions"/></label><small>This procedure collects matching saved records and produces a local review output. It does not claim to have refreshed every provider.</small><button disabled={busy || !name.trim() || !description.trim() || (!tasks && !query.trim())}>{editingId ? "Save revised draft" : "Create executable draft"}</button></form></details>
    </section><section className="card surface"><h3>{selectedCurrent?.spec?.name ?? 'Choose a procedure'}</h3>{selectedCurrent ? <><p>{selectedCurrent.spec.description}</p><button className="quiet" onClick={() => { setEditingId(selectedCurrent.capability_id); setName(selectedCurrent.spec.name); setDescription(selectedCurrent.spec.description || ''); setTasks(Boolean(selectedCurrent.spec.steps?.some(step => step.tool === 'list_tasks'))); setQuery(String(selectedCurrent.spec.steps?.find(step => step.tool === 'search_evidence')?.args.query ?? '')); }}>Edit procedure</button>{!selectedCurrent.spec.steps?.length && <p>This older definition has no executable steps. Edit it before testing or activation.</p>}<ol className="workflow-steps">{(selectedCurrent.spec.steps ?? []).map(step => <li key={step.id}>{step.tool === 'list_tasks' ? 'Collect current tasks' : step.tool === 'search_evidence' ? `Find saved evidence: ${String(step.args.query ?? '')}` : step.tool === 'save_output' ? 'Save the collected result privately' : step.tool.replaceAll('_', ' ')}</li>)}</ol><p>{selectedCurrent.status} · {selectedCurrent.spec.context_id}</p><div className="focus-controls"><button className="quiet" disabled={busy} onClick={() => void execute('dry')}>Run synthetic fixtures</button><button className="quiet" disabled={busy} onClick={() => void execute('shadow')}>Run read-only shadow</button>{selectedCurrent.status !== 'active' ? <button disabled={busy} onClick={() => void perform(async () => { await workspace('capabilities.activate', { capabilityId: selectedCurrent.capability_id }); await refresh(); setNotice('The tested revision is active for in-scope local execution.'); })}>Activate tested version</button> : <button disabled={busy} onClick={() => void execute('active')}>Run now</button>}</div>
      <details className="schedule-editor"><summary>Schedule this procedure</summary><form className="local-create" onSubmit={event => { event.preventDefault(); void perform(async () => { await workspace('jobs.create', { capabilityId: selectedCurrent.capability_id, schedule: { kind: schedule, time, ...(schedule === 'weekly' ? { weekday: Number(weekday) } : {}), quiet_hours: [22, 8] }, timezone: zone, mode }); await refresh(); setNotice('Schedule saved. It runs only under the visible Jarvis lifecycle; launch at login is a separate setting.'); }); }}><label>Repeat<select value={schedule} onChange={event => setSchedule(event.target.value)}><option value="weekly">Weekly</option><option value="daily">Daily</option></select></label>{schedule === 'weekly' && <label>Day<select value={weekday} onChange={event => setWeekday(event.target.value)}>{['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map((day, index) => <option value={index} key={day}>{day}</option>)}</select></label>}<label>Local time<input type="time" value={time} onChange={event => setTime(event.target.value)} required/></label><label>Time zone<input value={zone} onChange={event => setZone(event.target.value)} required/></label><label>Execution<select value={mode} onChange={event => setMode(event.target.value)}><option value="shadow">Read-only shadow</option><option value="active">Active local workflow</option></select></label><button disabled={busy || (mode === 'active' && selectedCurrent.status !== 'active')}>Save schedule</button></form></details>
      {receipt && <section className="workflow-receipt"><h3>Execution {receipt.status}</h3><p>{receipt.evidence_class ?? 'Evidence class unavailable'} · {receipt.mode}</p>{receipt.error && <p role="alert">{receipt.error}</p>}{receipt.steps?.map(step => <details key={step.id}><summary>{step.tool.replaceAll('_', ' ')} · {step.status}</summary><pre>{typeof step.output === 'string' ? step.output : JSON.stringify(step.output, null, 2)}</pre></details>)}{receipt.outputs && <details><summary>Complete output</summary><pre>{JSON.stringify(receipt.outputs, null, 2)}</pre></details>}</section>}</> : <p>Open a saved procedure to inspect its steps, execute it, and see the actual result.</p>}</section></div>
    <section className="card surface scheduled-jobs"><h3>Schedules and durable jobs</h3><div className="setting"><span>Run scheduled work<small>Full Quit stops owned jobs. Missed checks resume when Jarvis runs again.</small></span><select aria-label="Scheduled work lifecycle" value={lifecycle} disabled={busy} onChange={event => { const mode = event.target.value; void perform(async () => { await workspace('jobs.lifecycle', { mode }); await refresh(); }); }}><option value="off">Off</option><option value="while-jarvis-runs">While Jarvis runs</option></select></div>{!jobs.length && <p>No scheduled jobs in this context. Saving a cadence is followed by an owned execution receipt when it actually runs.</p>}<div className="item-list">{jobs.map(job => <article key={job.job_id}><strong>{job.spec?.name ?? 'Owned job'}</strong><p>{job.status} · {job.mode} · {job.timezone}</p><p>Next: {job.next_run ? new Date(job.next_run).toLocaleString() : 'No next run'}<br/>Last: {job.last_run ? `${new Date(job.last_run).toLocaleString()} · ${job.last_status}` : 'Not run yet'}{job.last_result?.change_state && ` · ${job.last_result.change_state}`}</p><div className="focus-controls"><button className="quiet" disabled={busy || job.status === 'cancelled'} onClick={() => void perform(async () => { await workspace(job.status === 'paused' ? 'jobs.resume' : 'jobs.pause', { jobId: job.job_id }); await refresh(); })}>{job.status === 'paused' ? 'Resume' : 'Pause'}</button><button className="quiet" disabled={busy || job.status === 'cancelled'} onClick={() => void perform(async () => { const result = await workspace<Receipt>('jobs.run', { jobId: job.job_id }); setReceipt(result); await refresh(); })}>Run job now</button><button className="quiet" disabled={busy || job.status === 'cancelled'} onClick={() => void perform(async () => { await workspace('jobs.cancel', { jobId: job.job_id }); await refresh(); })}>Cancel job</button>{job.last_result && <button className="quiet" onClick={() => { setReceipt(job.last_result!); setSelected(capabilities.find(item => item.capability_id === job.capability_id) ?? null); }}>View last result</button>}</div></article>)}</div></section>
  </section>;
}
