import { useRef, useState } from 'react';
import { invoke } from './transport';
export interface BrowserSelection {selectionId:string;grantId:string;label:string;accountLabel:string;profileLabel:string;windowLabel:string;expiresAt:string;status:'selected';}
interface Target {targetId:string;label:string;accountLabel:string;profileLabel:string;windowLabel:string;}
interface Grant {grant_id:string;title:string;account_id:string;profile:string;operations:string[];status:string;expired:boolean;}
export function BrowserContext({sessionId,selection,ensureSession,onSelect}:{sessionId:string|null;selection?:BrowserSelection;ensureSession:()=>Promise<string>;onSelect:(sessionId:string,value:BrowserSelection|undefined)=>void}){
 const [targets,setTargets]=useState<Target[]>([]);const [targetId,setTargetId]=useState('');const [limitations,setLimitations]=useState('');
 const [grants,setGrants]=useState<Grant[]|null>(null);const [grantId,setGrantId]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const lock=useRef(false);
 async function choose(){if(lock.current||!grantId||!targetId)return;lock.current=true;setBusy(true);setNotice('');try{const origin= sessionId??await ensureSession();const result=await invoke<BrowserSelection|{cancelled:true}>('select_browser_context',{sessionId:origin,grantId,targetId});if('cancelled'in result)return;if(result.status!=='selected'||result.grantId!==grantId||!result.selectionId)throw new Error('Native browser selection did not return an owned receipt');onSelect(origin,result);setGrants(null);}catch(e){setNotice(String(e));}finally{lock.current=false;setBusy(false);}}
 return <div className="browser-context"><button type="button" className="quiet" disabled={busy} onClick={()=>{setBusy(true);setNotice('');void invoke<{grants:Grant[]}>('permissions_operation',{operation:'snapshot',request:{}}).then(value=>{if(!Array.isArray(value?.grants))throw new Error('Permission inventory unavailable');const active=value.grants.filter(g=>g.status==='active'&&!g.expired&&g.operations.some(op=>op.startsWith('browser.')));setGrants(active);setGrantId(active[0]?.grant_id??'');}).catch(e=>setNotice(String(e))).finally(()=>setBusy(false));}}>Choose browser context</button>{selection&&<span>{selection.accountLabel} · {selection.profileLabel} · {selection.windowLabel} · {new Date(selection.expiresAt).getTime()>Date.now()?'Selected target; checked again when used':'Selection expired'}<button type="button" className="quiet" onClick={()=>{if(sessionId)onSelect(sessionId,undefined);}}>Clear selection</button></span>}{grants&&<section className="navigation-preview"><strong>Choose the authority for this browser task</strong><p>The native selector shows actual observed windows or tabs and asks you to confirm the exact target. Configured account names alone do not verify a signed-in account.</p>{grants.length?<><label>Active browser grant<select disabled={busy} value={grantId} onChange={e=>{setGrantId(e.target.value);setTargets([]);setTargetId('');}}>{grants.map(g=><option key={g.grant_id} value={g.grant_id}>{g.title} · {g.account_id} · {g.profile}</option>)}</select></label><button type="button" disabled={busy||!grantId} onClick={()=>{setBusy(true);setNotice('');void invoke<{data:Target[];limitations?:string|string[]}>('browser_targets',{grantId}).then(value=>{if(!Array.isArray(value.data))throw new Error('Observed browser targets unavailable');setTargets(value.data);setTargetId('');setLimitations(Array.isArray(value.limitations)?value.limitations.join(' · '):value.limitations??'');}).catch(e=>setNotice(String(e))).finally(()=>setBusy(false));}}>Show observed browser targets</button>{limitations&&<p>{limitations}</p>}{targets.length>0&&<><label>Observed target<select value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">Select exact window or tab</option>{targets.map(target=><option key={target.targetId} value={target.targetId}>{target.label} · {target.accountLabel} · {target.profileLabel} · {target.windowLabel}</option>)}</select></label><button type="button" disabled={busy||!targetId} onClick={()=>void choose()}>Select and review actual browser target</button></>}</>:<p>No active browser grant is available. Add a scoped task grant in Permissions first.</p>}<button type="button" className="quiet" onClick={()=>setGrants(null)}>Close chooser</button></section>}{notice&&<p role="status">{notice}</p>}</div>;
}
