import { useRef, useState } from 'react';
import type { ConversationRun } from './conversationRuns';
export function RunRecovery({run,recover,retryIncomplete}:{run?:ConversationRun;recover:(action:'retry-save'|'acknowledge-unknown')=>Promise<void>;retryIncomplete:()=>Promise<void>}) {
 const [busy,setBusy]=useState(false);const lock=useRef(false);
 if(!run||(run.phase!=='unresolved'&&!run.persistencePending&&!run.reportRecovery))return null;
 const finalIncomplete=run.reportRecovery?.kind==='final-incomplete'&&!run.persistencePending;
 const retained=run.reportRecovery?.kind==='retained-response'&&!run.persistencePending;
 const known=(finalIncomplete||retained||run.reportRecovery?.kind==='known-incomplete')&&!run.persistencePending;
 async function act(work:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);try{await work();}finally{lock.current=false;setBusy(false);}}
 return <section className="run-recovery" role="status"><strong>This request needs recovery</strong><p>{run.persistencePending?'The result is retained, but saving the canonical conversation needs another attempt. This does not rerun the action.':finalIncomplete?'This starts a new paid final model request using the completed evidence processing. The old failed turn is not replayed, and evidence extraction is not repeated.':retained?'Local validation reuses only valid source-backed work from the saved response; unsupported claims remain rejected. Remaining extraction and final synthesis may require paid model calls.':known?'The model returned a known incomplete report result. Retry starts or resumes the same new request and reuses completed evidence processing; the earlier turn is not repeated.':'No accepted completed result is available. Continuing does not confirm success, undo anything, or repeat the earlier action.'}</p>{run.persistencePending?<button disabled={busy} type="button" className="quiet" onClick={()=>void act(()=>recover('retry-save'))}>Retry saving this exact result</button>:known?<button disabled={busy} type="button" className="quiet" onClick={()=>void act(retryIncomplete)}>{finalIncomplete?'Retry final report composition':retained?'Recover retained evidence and continue':'Retry known incomplete report processing'}</button>:<button disabled={busy} type="button" className="quiet" onClick={()=>void act(()=>recover('acknowledge-unknown'))}>Continue without retrying the earlier action</button>}</section>;
}
