import { useEffect, useRef, useState } from 'react';
import { invoke } from './transport';
import { listen } from './transport';
interface WakeStatus {state:string;available:boolean;phrase?:string;hint?:string;missing?:string[];generation?:string;}
export function WakeControl({visible,occupied,onWake}:{visible:boolean;occupied:boolean;onWake:()=>Promise<void>}){
 const [status,setStatus]=useState<WakeStatus>({state:'off',available:false});const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const current=useRef({occupied,onWake});current.current={occupied,onWake};const generation=useRef<string|undefined>(undefined);const seen=useRef(new Set<string>());const firing=useRef(false);
 async function control(operation:string){const value=await invoke<WakeStatus>('wake_control',{operation});if(!value?.state)throw new Error('Optional wake service unavailable');generation.current=value.generation;setStatus(value);return value;}
 useEffect(()=>{void control('status').catch(e=>setNotice(String(e)));const stop=listen<{eventId:string;generation:string}>('jarvis-wake',event=>{const value=event.payload;if(!value?.eventId||value.generation!==generation.current||seen.current.has(value.eventId)||firing.current)return;seen.current.add(value.eventId);if(seen.current.size>100)seen.current.delete(seen.current.values().next().value!);if(current.current.occupied)return;firing.current=true;setStatus(old=>({...old,state:'paused'}));void current.current.onWake().finally(()=>{firing.current=false;});});return()=>{void stop.then(unlisten=>unlisten());};},[]);
 useEffect(()=>{if(!['listening','paused'].includes(status.state))return;void control(occupied?'pause':'resume').catch(e=>setNotice(String(e)));},[occupied]);
 return <section className="card surface" hidden={!visible}><h3>Optional wake word</h3><p>Off by default. Detection stays on this Mac while Jarvis runs and pauses during voice capture or another request. Wake starts the existing Talk flow; it never submits a separate duplicate message.</p><p>{status.phrase||'Hey Hermes'} · {status.state}</p>{status.hint&&<p>{status.hint}</p>}{status.missing?.length? <p>Unavailable: {status.missing.join(', ')}</p>:null}<button className="quiet" disabled={busy||(!status.available&&status.state==='off')||(occupied&&status.state==='off')} onClick={()=>{setBusy(true);setNotice('');void control(['listening','paused'].includes(status.state)?'stop':'start').catch(e=>setNotice(String(e))).finally(()=>setBusy(false));}}>{['listening','paused'].includes(status.state)?'Turn wake off':'Enable wake while Jarvis runs'}</button><button className="quiet" disabled={busy} onClick={()=>void control('status').catch(e=>setNotice(String(e)))}>Check optional wake support</button>{notice&&<p role="status">{notice}</p>}</section>;
}
